#ifndef __DEVICE_SAMSUNG_H__
#define __DEVICE_SAMSUNG_H__

#define SAMSUNG_POWER_TOGGLE       "Samsung_power_toggle"
#define SAMSUNG_SOURCE             "Samsung_source"
#define SAMSUNG_HDMI               "Samsung_hdmi"
#define SAMSUNG_NUM_1              "Samsung_num_1"
#define SAMSUNG_NUM_2              "Samsung_num_2"
#define SAMSUNG_NUM_3              "Samsung_num_3"
#define SAMSUNG_NUM_4              "Samsung_num_4"
#define SAMSUNG_NUM_5              "Samsung_num_5"
#define SAMSUNG_NUM_6              "Samsung_num_6"
#define SAMSUNG_NUM_7              "Samsung_num_7"
#define SAMSUNG_NUM_8              "Samsung_num_8"
#define SAMSUNG_NUM_9              "Samsung_num_9"
#define SAMSUNG_NUM_0              "Samsung_num_0"
#define SAMSUNG_TTXMIX             "Samsung_ttxmix"
#define SAMSUNG_PRECH              "Samsung_prech"
#define SAMSUNG_VOL_MINUS          "Samsung_vol_minus"
#define SAMSUNG_VOL_PLUS           "Samsung_vol_plus"
#define SAMSUNG_MUTE_TOGGLE        "Samsung_mute_toggle"
#define SAMSUNG_CHLIST             "Samsung_chlist"
#define SAMSUNG_CHANNEL_UP         "Samsung_channel_up"
#define SAMSUNG_CHANNEL_DOWN       "Samsung_channel_down"
#define SAMSUNG_MENU               "Samsung_menu"
#define SAMSUNG_APPS               "Samsung_apps"
#define SAMSUNG_GUIDE              "Samsung_guide"
#define SAMSUNG_TOOLS              "Samsung_tools"
#define SAMSUNG_INFO               "Samsung_info"
#define SAMSUNG_UP                 "Samsung_up"
#define SAMSUNG_DOWN               "Samsung_down"
#define SAMSUNG_LEFT               "Samsung_left"
#define SAMSUNG_RIGHT              "Samsung_right"
#define SAMSUNG_SELECT             "Samsung_select"
#define SAMSUNG_RETURN             "Samsung_return"
#define SAMSUNG_EXIT               "Samsung_exit"
#define SAMSUNG_KEY_A              "Samsung_key_a"
#define SAMSUNG_KEY_B              "Samsung_key_b"
#define SAMSUNG_KEY_C              "Samsung_key_c"
#define SAMSUNG_KEY_D              "Samsung_key_d"
#define SAMSUNG_FAMILYSTORY        "Samsung_familystory"
#define SAMSUNG_SEARCH             "Samsung_search"
#define SAMSUNG_DUALI_II           "Samsung_duali-ii"
#define SAMSUNG_SUPPORT            "Samsung_support"
#define SAMSUNG_PSIZE              "Samsung_psize"
#define SAMSUNG_ADSUBT             "Samsung_adsubt"
#define SAMSUNG_REWIND             "Samsung_rewind"
#define SAMSUNG_PAUSE              "Samsung_pause"
#define SAMSUNG_FASTFORWARD        "Samsung_fastforward"
#define SAMSUNG_RECORD             "Samsung_record"
#define SAMSUNG_PLAY               "Samsung_play"
#define SAMSUNG_STOP               "Samsung_stop"
#define SAMSUNG_POWER_OFF          "Samsung_power_off"
#define SAMSUNG_POWER_ON           "Samsung_power_on"
#define SAMSUNG_INPUT_HDMI_1       "Samsung_input_hdmi_1"
#define SAMSUNG_INPUT_HDMI_2       "Samsung_input_hdmi_2"
#define SAMSUNG_INPUT_HDMI_3       "Samsung_input_hdmi_3"
#define SAMSUNG_INPUT_HDMI_4       "Samsung_input_hdmi_4"
#define SAMSUNG_INPUT_COMPONENT    "Samsung_input_component"
#define SAMSUNG_INPUT_TV           "Samsung_input_tv"

void register_device_samsung();

#endif /*__DEVICE_SAMSUNG_H__*/
