#pragma once

#include "windows_linux/battery_hal_windows_linux.h"
#include "windows_linux/hardware_general_hal_windows_linux.h"
#include "windows_linux/heapUsage_hal_windows_linux.h"
#include "windows_linux/infrared_receiver_hal_windows_linux.h"
#include "windows_linux/infrared_sender_hal_windows_linux.h"
#include "windows_linux/keyboard_ble_hal_windows_linux.h"
#include "windows_linux/keypad_keys_hal_windows_linux.h"
#include "windows_linux/lvgl_hal_windows_linux.h"
#include "windows_linux/mqtt_hal_windows_linux.h"
#include "windows_linux/preferencesStorage_hal_windows_linux.h"
#include "windows_linux/sd_card_hal_windows_linux.h"
#include "windows_linux/sleep_hal_windows_linux.h"
#include "windows_linux/tft_hal_windows_linux.h"
#include "windows_linux/user_led_hal_windows_linux.h"
#include "windows_linux/espnow_hal_windows_linux.h"
