#pragma once

#include "ESP32/battery_hal_esp32.h"
#include "ESP32/hardware_general_hal_esp32.h"
#include "ESP32/heapUsage_hal_esp32.h"
#include "ESP32/infrared_receiver_hal_esp32.h"
#include "ESP32/infrared_sender_hal_esp32.h"
#include "ESP32/keyboard_ble_hal_esp32.h"
#include "ESP32/keypad_keys_hal_esp32.h"
#include "ESP32/lvgl_hal_esp32.h"
#include "ESP32/mqtt_hal_esp32.h"
#include "ESP32/preferencesStorage_hal_esp32.h"
#include "ESP32/sd_card_hal_esp32.h"
#include "ESP32/sleep_hal_esp32.h"
#include "ESP32/tft_hal_esp32.h"
#include "ESP32/user_led_hal_esp32.h"
#include "ESP32/espnow_hal_esp32.h"
