#pragma once

extern uint16_t SAMSUNGBLURAY_POWER;
extern uint16_t SAMSUNGBLURAY_OPEN_CLOSE;
//extern uint16_t SAMSUNGBLURAY_1;
//extern uint16_t SAMSUNGBLURAY_2;
//extern uint16_t SAMSUNGBLURAY_3;
//extern uint16_t SAMSUNGBLURAY_4;
//extern uint16_t SAMSUNGBLURAY_5;
//extern uint16_t SAMSUNGBLURAY_6;
//extern uint16_t SAMSUNGBLURAY_7;
//extern uint16_t SAMSUNGBLURAY_8;
//extern uint16_t SAMSUNGBLURAY_9;
//extern uint16_t SAMSUNGBLURAY_0;
extern uint16_t SAMSUNGBLURAY_DISC_MENU;
//extern uint16_t SAMSUNGBLURAY_TITLE_POPUP;
extern uint16_t SAMSUNGBLURAY_PREVIOUS;
extern uint16_t SAMSUNGBLURAY_SKIP;
extern uint16_t SAMSUNGBLURAY_REW;
extern uint16_t SAMSUNGBLURAY_FF;
extern uint16_t SAMSUNGBLURAY_STOP;
extern uint16_t SAMSUNGBLURAY_PLAY;
extern uint16_t SAMSUNGBLURAY_PAUSE;
extern uint16_t SAMSUNGBLURAY_AUDIO;
extern uint16_t SAMSUNGBLURAY_HOME;
extern uint16_t SAMSUNGBLURAY_SUBTITLE;
extern uint16_t SAMSUNGBLURAY_TOOLS;
extern uint16_t SAMSUNGBLURAY_INFO;
extern uint16_t SAMSUNGBLURAY_CURSOR_UP;
extern uint16_t SAMSUNGBLURAY_LEFT;
extern uint16_t SAMSUNGBLURAY_ENTER;
extern uint16_t SAMSUNGBLURAY_RIGHT;
extern uint16_t SAMSUNGBLURAY_CURSOR_DOWN;
extern uint16_t SAMSUNGBLURAY_BACK;
extern uint16_t SAMSUNGBLURAY_EXIT;
extern uint16_t SAMSUNGBLURAY_KEY_A;
extern uint16_t SAMSUNGBLURAY_KEY_B;
extern uint16_t SAMSUNGBLURAY_KEY_C;
extern uint16_t SAMSUNGBLURAY_KEY_D;
//extern uint16_t SAMSUNGBLURAY_VIEW;
//extern uint16_t SAMSUNGBLURAY_A_B;
//extern uint16_t SAMSUNGBLURAY_REPEAT;
//extern uint16_t SAMSUNGBLURAY_SCREEN;

void register_device_samsungbluray();