#pragma once

// Only activate the commands that are used. Every command takes 100 bytes, wether used or not.
// extern uint16_t SAMSUNG_POWER_TOGGLE;
// extern uint16_t SAMSUNG_SOURCE;
// extern uint16_t SAMSUNG_HDMI;
extern uint16_t SAMSUNG_NUM_1;
extern uint16_t SAMSUNG_NUM_2;
extern uint16_t SAMSUNG_NUM_3;
extern uint16_t SAMSUNG_NUM_4;
extern uint16_t SAMSUNG_NUM_5;
extern uint16_t SAMSUNG_NUM_6;
extern uint16_t SAMSUNG_NUM_7;
extern uint16_t SAMSUNG_NUM_8;
extern uint16_t SAMSUNG_NUM_9;
extern uint16_t SAMSUNG_NUM_0;
// extern uint16_t SAMSUNG_TTXMIX;
// extern uint16_t SAMSUNG_PRECH;
// extern uint16_t SAMSUNG_VOL_MINUS;
// extern uint16_t SAMSUNG_VOL_PLUS;
// extern uint16_t SAMSUNG_MUTE_TOGGLE;
// extern uint16_t SAMSUNG_CHLIST;
extern uint16_t SAMSUNG_CHANNEL_UP;
extern uint16_t SAMSUNG_CHANNEL_DOWN;
extern uint16_t SAMSUNG_MENU;
// extern uint16_t SAMSUNG_APPS;
extern uint16_t SAMSUNG_GUIDE;
// extern uint16_t SAMSUNG_TOOLS;
// extern uint16_t SAMSUNG_INFO;
extern uint16_t SAMSUNG_UP;
extern uint16_t SAMSUNG_DOWN;
extern uint16_t SAMSUNG_LEFT;
extern uint16_t SAMSUNG_RIGHT;
extern uint16_t SAMSUNG_SELECT;
// extern uint16_t SAMSUNG_RETURN;
extern uint16_t SAMSUNG_EXIT;
// extern uint16_t SAMSUNG_KEY_A;
// extern uint16_t SAMSUNG_KEY_B;
// extern uint16_t SAMSUNG_KEY_C;
// extern uint16_t SAMSUNG_KEY_D;
// extern uint16_t SAMSUNG_FAMILYSTORY;
// extern uint16_t SAMSUNG_SEARCH;
// extern uint16_t SAMSUNG_DUALI_II;
// extern uint16_t SAMSUNG_SUPPORT;
// extern uint16_t SAMSUNG_PSIZE;
// extern uint16_t SAMSUNG_ADSUBT;
extern uint16_t SAMSUNG_REWIND;
extern uint16_t SAMSUNG_PAUSE;
extern uint16_t SAMSUNG_FASTFORWARD;
// extern uint16_t SAMSUNG_RECORD;
extern uint16_t SAMSUNG_PLAY;
// extern uint16_t SAMSUNG_STOP;
extern uint16_t SAMSUNG_POWER_OFF;
extern uint16_t SAMSUNG_POWER_ON;
extern uint16_t SAMSUNG_INPUT_HDMI_1;
extern uint16_t SAMSUNG_INPUT_HDMI_2;
extern uint16_t SAMSUNG_INPUT_HDMI_3;
// extern uint16_t SAMSUNG_INPUT_HDMI_4;
// extern uint16_t SAMSUNG_INPUT_COMPONENT;
extern uint16_t SAMSUNG_INPUT_TV;

void register_device_samsungTV();
